# Spring Boot PROD profile - MariaDB settings
server.port=8080

spring.h2.console.enabled=false

# DataSource
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://mariadb-container:3306/goorm_jpa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
spring.datasource.username=goorm-jpa
spring.datasource.password=${DB_PASSWORD:1234}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


# Logging (prod sensible defaults)
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate.orm.jdbc.extract=INFO

# Misc
spring.sql.init.mode=never

